backend:
  name: github
  repo: DEIN_GITHUB_USERNAME/homigo-website
  branch: production
  commit_messages:
    create: "content: create {{collection}} “{{slug}}”"
    update: "content: update {{collection}} “{{slug}}”"
    delete: "content: delete {{collection}} “{{slug}}”"

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "de"

collections:
  - name: "pages"
    label: "Seiten"
    folder: "content/pages"
    create: false
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "SEO Beschreibung", name: "seo_description", widget: "text", required: false }
      - { label: "Inhalt", name: "body", widget: "markdown" }

  - name: "collections"
    label: "Shop-Kollektionen"
    folder: "content/collections"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "SEO Beschreibung", name: "seo_description", widget: "text" }
      - { label: "Kurzbeschreibung", name: "excerpt", widget: "text" }
      - { label: "Inhalt", name: "body", widget: "markdown" }